package bootstrap

import (
	"fmt"
	"os"
)

// requiredSecretFiles mirrors deploy.sh's own preflight list exactly --
// generated by scripts/generate-authelia-secrets.sh, never committed.
// tink only ever checks these exist and streams their bytes on to `incus
// file push`; it never holds a secret's value as a Go string longer than
// that single copy needs to exist.
var requiredSecretFiles = []string{
	"secrets/reset_password_jwt_secret",
	"secrets/session_secret",
	"secrets/storage_encryption_key",
	"secrets/oidc_hmac_secret",
	"secrets/oidc.key",
	"authelia/users_database.yml",
}

// checkSecretsPresent reports every missing file at once, mirroring
// deploy.sh's own preflight loop -- run before anything is created or
// changed, so a fresh checkout fails fast instead of partway through.
func checkSecretsPresent(repoRoot string) error {
	var missing []string
	for _, rel := range requiredSecretFiles {
		path := repoRoot + "/" + rel
		if _, err := os.Stat(path); err != nil {
			missing = append(missing, rel)
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf(
			"missing required secret file(s): %v -- run scripts/generate-authelia-secrets.sh "+
				"(and fill in authelia/users_database.yml from the .example) before applying",
			missing,
		)
	}
	return nil
}
